[notebook]
dir = "~/notes"

[note]
language = "en"
default-title = "Untitled"
filename = "{{id}}-{{slug title}}"
extension = "md"
template = "note.md"
id-charset = "alphanum"
id-length = 8
id-case = "lower"

[extra]
author = "Guglielmo"

[format.markdown]
link-format = "wiki"
hashtags = true
colon-tags = true
multiword-tags = true

[tool]
editor = "nvim"
shell = "/usr/bin/zsh"
pager = "less -FIRX"
fzf-preview = "bat -p --color always {-1}"

[group.references]
paths = "references"

[group.references.note]
filename = "{{id}}"
template = "reference.md"

[lsp]

[lsp.diagnostics]
wiki-title = "hint"
dead-link = "error"

[lsp.completion]
note-label = "{{title-or-path}}"
note-filter-text = "{{title}} {{path}}"
note-detail = "{{filename-stem}}"

[alias]
conf = 'nvim "$HOME/.config/zk/config.toml"'
rm = "zk list --interactive --quiet --format '{{abs-path}}' --delimiter0 $@ \
  | xargs -0 rm -vf --"
